### ISSUE TITLE
Can't get Drag & Drop example to work outside of the repo

### ISSUE THREAD

**Issue by RobWalt** [aevyrie/bevy_mod_picking#257]
I literally just copy-pasted the code from [the example (`drag_and_drop.rs`)](https://github.com/aevyrie/bevy_mod_picking/blob/main/examples/drag_and_drop.rs) into an empty project and added the following `Cargo.toml`

```toml
[package]
name = "bevy_mod_picking_sanity_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11", features = ["wayland"] }
bevy_egui = "0.21"
bevy_eventlistener = "0.3"
bevy_mod_picking = "0.15"
```

I'm on wayland, so maybe that's it. It's weird though since the example runs in your repo when I run with `cargo run --release --example drag_and_drop`

Here's what it looks like on my machine. It's just unresponsive

![recording](https://github.com/aevyrie/bevy_mod_picking/assets/26892280/e3c124a9-0301-496f-a5b3-87d6ebd4de62)
