### ISSUE TITLE
Rapier backend doesn't work

### ISSUE THREAD

**Issue by Multirious** [aevyrie/bevy_mod_picking#307]
I was trying to get rapier backend to work for hours.
Then I tried the example `rapier.rs` copy pasted to my project which actually turns out that it doesn't works.

Tested with the following dependencies
```toml
[dependencies]
bevy = { version = "0.12.1" }
bevy_mod_picking = { version = "0.17.0", features = ["backend_rapier"]}
bevy_rapier3d = { version = "0.24.0", features = ["debug-render-3d"] }
```
